create TABLE IF NOT exists Genres(
    genre_id INTEGER PRIMARY KEY,
    name varchar(100) NOT NULL
);

create TABLE IF NOT exists Mpa(
    mpa_id INTEGER PRIMARY KEY,
    name varchar(100) NOT NULL
);

create TABLE if not exists Films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(1000) not null,
    releaseDate date not null,
    duration int not NULL,
    mpa_id int REFERENCES Mpa(mpa_id)
);

create table if not exists Users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100) NOT NULL,
    login varchar(100) not null,
    name varchar(100) not null,
    birthday date not null
);


-------- relation tables
create table if not exists Film_Genre(
    genre_id INTEGER REFERENCES Genres(genre_id),
    film_id INTEGER REFERENCES Films(film_id),
    constraint relationFilmGenre UNIQUE(genre_id, film_id)
);
create table if not exists Likes(
    film_id INTEGER REFERENCES Films(film_id),
    user_id INTEGER REFERENCES Users(user_id),
    constraint uniqueLikes UNIQUE(film_id, user_id)
);
create table if not exists Friends(
    user_id1 INTEGER REFERENCES Users(user_id),
    user_id2 INTEGER REFERENCES Users(user_id),
    constraint uniqueFriends UNIQUE(user_id1, user_id2),
    CHECK (user_id1 != user_id2)
)