CREATE TABLE IF NOT exists Genres(
    genre_id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT exists Mpa(
    mpa_id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE if not exists Films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    releaseDate DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER REFERENCES Mpa(mpa_id)
);

CREATE TABLE if not exists Users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    birthday DATE NOT NULL,
    CONSTRAINT uniqueEmails UNIQUE(email)
);


-------- relation TABLEs
CREATE TABLE if not exists Film_Genre(
    genre_id INTEGER REFERENCES Genres(genre_id),
    film_id INTEGER REFERENCES Films(film_id),
    CONSTRAINT relationFilmGenre UNIQUE(genre_id, film_id)
);
CREATE TABLE if not exists Likes(
    film_id INTEGER REFERENCES Films(film_id),
    user_id INTEGER REFERENCES Users(user_id),
    CONSTRAINT uniqueLikes UNIQUE(film_id, user_id)
);
CREATE TABLE if not exists Friends(
    user_id1 INTEGER REFERENCES Users(user_id),
    user_id2 INTEGER REFERENCES Users(user_id),
    CONSTRAINT uniqueFriends UNIQUE(user_id1, user_id2),
    CHECK (user_id1 != user_id2)
)